spring.application.name=vaultdocs

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2
spring.ai.ollama.embedding.model=nomic-embed-text
spring.ai.ollama.init.pull-model-strategy=when_missing

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

gemini-model-url=${URL}
gemini-api-key=${API_KEY}